import { Router, type IRouter } from "express";
import healthRouter from "./health";
import leadsRouter from "./leads";
import applicationsRouter from "./applications";
import incidentsRouter from "./incidents";
import usersRouter from "./users";
import employeesRouter from "./employees";
import portalRouter from "./portal";
import whatsappWebhookRouter from "./whatsapp-webhook";
import trelloRouter from "./trello";
import anticiposRouter from "./anticipos";
import { aliasRouter } from "./alias";
import { waConfigRouter } from "./wa-config";
import emergenciasRouter from "./emergencias";
import tareasRouter from "./tareas";
import reportesRouter from "./reportes";
import cmsRouter from "./cms";
import simuladorRouter from "./simulador";
import operacionesRouter from "./operaciones";
import { eventosRrhhRouter } from "./eventos-rrhh";
import { rrhhAlertasRouter } from "./rrhh-alertas";
import sedesRouter from "./sedes";
import coberturaRouter from "./cobertura";

const router: IRouter = Router();

router.use(healthRouter);
router.use(leadsRouter);
router.use(applicationsRouter);
router.use(incidentsRouter);
router.use(usersRouter);
router.use(employeesRouter);
router.use(portalRouter);
router.use(whatsappWebhookRouter);
router.use(trelloRouter);
router.use(anticiposRouter);
router.use(aliasRouter);
router.use(waConfigRouter);
router.use(emergenciasRouter);
router.use(tareasRouter);
router.use(reportesRouter);
router.use(cmsRouter);
router.use(simuladorRouter);
router.use(operacionesRouter);
router.use(eventosRrhhRouter);
router.use(rrhhAlertasRouter);
router.use(sedesRouter);
router.use(coberturaRouter);

export default router;
