import { Router, type IRouter } from "express";
import healthRouter from "./health";
import leadsRouter from "./leads";
import applicationsRouter from "./applications";
import incidentsRouter from "./incidents";
import usersRouter from "./users";
import employeesRouter from "./employees";
import portalRouter from "./portal";
import whatsappWebhookRouter from "./whatsapp-webhook";
import trelloRouter from "./trello";
import anticiposRouter from "./anticipos";
import { aliasRouter } from "./alias";
import { waConfigRouter } from "./wa-config";
import emergenciasRouter from "./emergencias";
import tareasRouter from "./tareas";
import reportesRouter from "./reportes";
import cmsRouter from "./cms";
import simuladorRouter from "./simulador";
import operacionesRouter from "./operaciones";
import zonasRouter from "./zonas";
import { eventosRrhhRouter } from "./eventos-rrhh";
import { rrhhAlertasRouter } from "./rrhh-alertas";
import sedesRouter from "./sedes";
import coberturaRouter from "./cobertura";
import fichaRouter from "./ficha";
import { nominaRouter } from "./nomina";
import { prePlanillaRouter } from "./pre-planilla";
import { turnosRouter } from "./turnos";
import storageRouter from "./storage";
import kpiRouter from "./kpi";
import { solicitudesCambioRouter } from "./solicitudes-cambio";
import { solicitudesServicioRouter } from "./solicitudes-servicio";
import { incentivosRouter } from "./incentivos";
import { planillaRouter } from "./planilla";
import adminResetRouter from "./admin-reset";
import { planificacionFuturaRouter } from "./planificacion-futura";
import { vacacionesRouter } from "./vacaciones";
import { vehiculosRouter } from "./vehiculos";
import { armeriaRouter } from "./armeria";
import { solicitudesEliminacionRouter } from "./solicitudes-eliminacion";
import cambiosSalarialesRouter from "./cambios-salariales";
import { prestacionesRouter } from "./prestaciones";
import dashboardRouter from "./dashboard";
import { planillasEspecialesRouter } from "./planillas-especiales";
import { libroSalariosRouter } from "./libro-salarios";

const router: IRouter = Router();

router.use(healthRouter);
router.use(leadsRouter);
router.use(applicationsRouter);
router.use(incidentsRouter);
router.use(usersRouter);
router.use(employeesRouter);
router.use(portalRouter);
router.use(whatsappWebhookRouter);
router.use(trelloRouter);
router.use(anticiposRouter);
router.use(aliasRouter);
router.use(waConfigRouter);
router.use(emergenciasRouter);
router.use(tareasRouter);
router.use(reportesRouter);
router.use(cmsRouter);
router.use(simuladorRouter);
router.use(operacionesRouter);
router.use(zonasRouter);
router.use(eventosRrhhRouter);
router.use(rrhhAlertasRouter);
router.use(sedesRouter);
router.use(coberturaRouter);
router.use(fichaRouter);
router.use(nominaRouter);
router.use(prePlanillaRouter);
router.use(turnosRouter);
router.use(storageRouter);
router.use(kpiRouter);
router.use(solicitudesCambioRouter);
router.use(solicitudesServicioRouter);
router.use(incentivosRouter);
router.use(planillaRouter);
router.use(adminResetRouter);
router.use(planificacionFuturaRouter);
router.use(vacacionesRouter);
router.use(vehiculosRouter);
router.use(armeriaRouter);
router.use(solicitudesEliminacionRouter);
router.use(cambiosSalarialesRouter);
router.use(prestacionesRouter);
router.use(dashboardRouter);
router.use(planillasEspecialesRouter);
router.use(libroSalariosRouter);

export default router;
