// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/carnets-pvc/Elite.tsx": () => import("../components/mockups/carnets-pvc/Elite.tsx"),
  "./components/mockups/carnets-pvc/Moderno.tsx": () => import("../components/mockups/carnets-pvc/Moderno.tsx"),
  "./components/mockups/fichaje-qr/AgenteCredencial.tsx": () => import("../components/mockups/fichaje-qr/AgenteCredencial.tsx"),
  "./components/mockups/fichaje-qr/FichajePuesto.tsx": () => import("../components/mockups/fichaje-qr/FichajePuesto.tsx"),
  "./components/mockups/fichaje-qr/Supervision.tsx": () => import("../components/mockups/fichaje-qr/Supervision.tsx")
};
